[2024-09-02T13:51:26.701+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark-submit-test.spark-submit-test manual__2024-09-02T13:45:52.571628+00:00 [queued]>
[2024-09-02T13:51:26.712+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark-submit-test.spark-submit-test manual__2024-09-02T13:45:52.571628+00:00 [queued]>
[2024-09-02T13:51:26.712+0000] {taskinstance.py:1359} INFO - Starting attempt 4 of 5
[2024-09-02T13:51:26.730+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): spark-submit-test> on 2024-09-02 13:45:52.571628+00:00
[2024-09-02T13:51:26.741+0000] {standard_task_runner.py:57} INFO - Started process 6413 to run task
[2024-09-02T13:51:26.747+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark-submit-test', 'spark-submit-test', 'manual__2024-09-02T13:45:52.571628+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/spark-submit-test.py', '--cfg-path', '/tmp/tmpc3hk66pj']
[2024-09-02T13:51:26.748+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask spark-submit-test
[2024-09-02T13:51:26.826+0000] {task_command.py:415} INFO - Running <TaskInstance: spark-submit-test.spark-submit-test manual__2024-09-02T13:45:52.571628+00:00 [running]> on host 84faf8a8b4b8
[2024-09-02T13:51:26.917+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark-submit-test' AIRFLOW_CTX_TASK_ID='spark-submit-test' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T13:45:52.571628+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-02T13:45:52.571628+00:00'
[2024-09-02T13:51:26.926+0000] {base.py:73} INFO - Using connection ID 'spark_mumix' for task execution.
[2024-09-02T13:51:26.927+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.executor.memory=0.3G --conf spark.executor.cores=1 --conf spark.executor.instances=1 --name arrow-spark ./spark-scripts/spark-test.py
[2024-09-02T13:51:28.790+0000] {spark_submit.py:491} INFO - Exception in thread "main" org.apache.spark.SparkException: Executor memory must be a positive number
[2024-09-02T13:51:28.792+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-09-02T13:51:28.792+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:254)
[2024-09-02T13:51:28.792+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-09-02T13:51:28.792+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-09-02T13:51:28.793+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1029)
[2024-09-02T13:51:28.793+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1029)
[2024-09-02T13:51:28.793+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-09-02T13:51:28.793+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-09-02T13:51:28.793+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-09-02T13:51:28.793+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-09-02T13:51:28.814+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.executor.memory=0.3G --conf spark.executor.cores=1 --conf spark.executor.instances=1 --name arrow-spark ./spark-scripts/spark-test.py. Error code is: 1.
[2024-09-02T13:51:28.818+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=spark-submit-test, task_id=spark-submit-test, execution_date=20240902T134552, start_date=20240902T135126, end_date=20240902T135128
[2024-09-02T13:51:28.830+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 29 for task spark-submit-test (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.executor.memory=0.3G --conf spark.executor.cores=1 --conf spark.executor.instances=1 --name arrow-spark ./spark-scripts/spark-test.py. Error code is: 1.; 6413)
[2024-09-02T13:51:28.854+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-02T13:51:28.871+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
